# Generated by Django 4.1.7 on 2023-03-12 12:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_productcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Mobile number')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('products', models.ManyToManyField(related_name='orders', to='webapp.product', verbose_name='Goods')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.product', verbose_name='Товар')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='quantities',
            field=models.ManyToManyField(related_name='quantities', through='webapp.ProductQuantity', to='webapp.product', verbose_name='Quantities'),
        ),
    ]
