# Generated by Django 4.1.7 on 2023-03-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_order_quantities_alter_productquantity_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductQuantity',
            new_name='OrderProduct',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantities',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='webapp.product', verbose_name='Goods'),
        ),
    ]
